"""code_length

Revision ID: 8585a191d849
Revises: b45051cbf5b4
Create Date: 2021-11-14 21:48:15.559251

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '8585a191d849'
down_revision = 'b45051cbf5b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction', 'code',
               existing_type=sa.VARCHAR(32))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction', 'code',
               existing_type=sa.VARCHAR(10))
    # ### end Alembic commands ###
