"""add_is_active

Revision ID: 9abd6c35f12c
Revises: 8e9ef30d667a
Create Date: 2021-10-25 01:38:19.064336

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '9abd6c35f12c'
down_revision = '8e9ef30d667a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_user_is_active'), 'user', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_is_active'), table_name='user')
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###
