"""add_ticker_relationship

Revision ID: b45051cbf5b4
Revises: 61f0221088e4
Create Date: 2021-10-26 11:52:41.876994

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'b45051cbf5b4'
down_revision = '61f0221088e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('ticker_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_transaction_ticker_id'), 'transaction', ['ticker_id'], unique=False)
    op.create_foreign_key(None, 'transaction', 'ticker', ['ticker_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_index(op.f('ix_transaction_ticker_id'), table_name='transaction')
    op.drop_column('transaction', 'ticker_id')
    # ### end Alembic commands ###
